name: Auto Update Products to Neon
on:
  schedule:
    - cron: '0 0 * * *' # يعمل تلقائياً كل يوم الساعة 12 منتصف الليل
  workflow_dispatch: # يسمح لك بتشغيله يدوياً الآن

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Update Products Data to Neon
        env:
          ADMITAD_BASE64: ${{ secrets.ADMITAD_BASE64 }}
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
        run: node updateProducts.cjs
