name: "Raqqa Cron Job"

on:
  schedule:
    # سيتم التنفيذ في الساعة 06:00 و 18:00 بتوقيت UTC
    # وهو ما يعادل 9:00 صباحاً و 9:00 مساءً بتوقيت القاهرة
    - cron: "0 6,18 * * *"
  workflow_dispatch:

jobs:
  run_notifications:
    runs-on: ubuntu-latest
    steps:
      - name: "Call Raqqa API"
        run: |
          curl -X GET "https://raqqa-hjl8.vercel.app/api/get-notifications" \
          -H "Content-Type: application/json" \
          -H "zazotona: 12sonds25" \
          -v
