name: "Raqqa Cron Job"

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run_notifications:
    runs-on: ubuntu-latest
    steps:
      - name: "Call Raqqa API"
        run: |
          curl -X GET "https://raqqa-hjl8.vercel.app/api/get-notifications" \
          -H "Content-Type: application/json" \
          -H "zazotona: 12sonds25" \
          -v
